global:
  # How frequently to scrape targets by default.
  scrape_interval: 10s

  # How long until a scrape request times out.
  # scrape_timeout: <duration> | default = 10s ]

  # How frequently to evaluate rules.
  #
scrape_configs:
  - job_name: "app"
    static_configs:
      - targets: ["app:2112"]

